### ISSUE TITLE
Explain gnome-settings-daemon D-Bus access

### ISSUE THREAD

**Issue by hadess** [flathub/org.gnome.Reversi#4]
I don't think that this access should be necessary:
```
 "--talk-name=org.gnome.SettingsDaemon.Color"
```

**Comment by nedrichards** [comment]
It's used here https://gitlab.gnome.org/GNOME/iagno/-/blob/master/src/night-light-monitor.vala#L127

of course in modern GNOME systems this should likely be ported to the newer style preference checks but until now this is actually used by the app.
